# © 2022 Amazon Web Services, Inc. or its affiliates. All Rights Reserved.

# This AWS Content is provided subject to the terms of the AWS Customer Agreement
# available at http://aws.amazon.com/agreement or other written agreement between
# Customer and either Amazon Web Services

AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: proxySoapServer

Resources:
  PostOfficesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs14.x
      Events:
        PostOfficesApi:
          Type: Api
          Properties:
            Path: /
            Method: post

Outputs:
  PostOffices:
    Description: "Test the API Gateway endpoint URL for Prod stage for PostOffices"
    Value: !Sub 'curl -i -X POST https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ -d ''{"data": 40325465}'''

  WatchLogsLocally:
    Description: "To watch the logs locally, use the following command"
    Value: !Sub "sam logs -n PostOfficesFunction --stack-name soapProxy --tail"
